try {
  throw new Error('try Error')
} catch (e) {
  throw new Error('catch Error')
  // console.log(e)
}